package prev26lang.phase.finasm;

import java.io.*;
import java.util.*;

import prev26lang.common.report.*;
import prev26lang.phase.*;
import prev26lang.phase.asmgen.*;
import prev26lang.phase.memory.*;
import prev26lang.phase.regall.*;

/**
 * Final assembly phase for the Ripes RV64IM simulator.
 */
public class FinAsm extends Phase {

	/** Scratch register reserved for final-phase address and size calculations. */
	private static final String SCRATCH = "x3";

	/** Ripes environment-call register for the first argument/result (a0). */
	private static final String SYSCALL_ARG = "x10";

	/** Ripes environment-call register for the call number (a7). */
	private static final String SYSCALL_ID = "x17";

	/** Final assembly lines. */
	private final Vector<String> lines;

	/**
	 * Phase construction.
	 */
	public FinAsm() {
		super("finasm");
		lines = new Vector<String>();
	}

	/**
	 * Emits Ripes-ready final assembly and writes it to a destination file.
	 * 
	 * @param dataChunks Static data chunks.
	 * @param codeChunks Register-allocated code chunks.
	 * @param registers Register maps matching {@code codeChunks}.
	 * @param dstFileName Destination assembly file.
	 */
	public void emit(
		final Vector<ASM.DataChunk> dataChunks,
		final Vector<ASM.CodeChunk> codeChunks,
		final Vector<LinkedHashMap<MEM.Temp, String>> registers,
		final String dstFileName
	) {
		if (codeChunks.size() != registers.size())
			throw new Report.InternalError();

		lines.clear();
		emitData(dataChunks);
		emitText(codeChunks, registers);
		write(dstFileName);
	}

	/**
	 * Returns final assembly lines.
	 */
	public Vector<String> lines() {
		return new Vector<String>(lines);
	}

	/**
	 * Emits the data section generated by assembly generation.
	 */
	private void emitData(final Vector<ASM.DataChunk> dataChunks) {
		if (dataChunks.isEmpty())
			return;

		lines.add(".data");
		for (final ASM.DataChunk dataChunk : dataChunks)
			lines.addAll(dataChunk.format());
		lines.add("");
	}

	/**
	 * Emits bootstrap code, compiled functions, and Ripes runtime routines.
	 */
	private void emitText(
		final Vector<ASM.CodeChunk> codeChunks,
		final Vector<LinkedHashMap<MEM.Temp, String>> registers
	) {
		lines.add(".text");
		lines.add(".globl main");
		emitBootstrap();

		for (int c = 0; c < codeChunks.size(); c++)
			emitCodeChunk(codeChunks.get(c), registers.get(c));

		emitRuntime();
	}

	/**
	 * Emits Ripes startup code that calls the compiled main function.
	 */
	private void emitBootstrap() {
		lines.add("main:");
		lines.add("  addi x2, x2, -16");
		lines.add("  sd x0, 0(x2)");
		lines.add("  jal x1, _main");

		// emitPrintString("Program exited with value: ");

		// lines.add("  ld " + SYSCALL_ARG + ", 0(x2)");
		// lines.add("  addi " + SYSCALL_ID + ", x0, 1");
		// lines.add("  ecall");
		// emitPrintChar('\n');
		
		lines.add("  addi x2, x2, 16");
		lines.add("  addi " + SYSCALL_ID + ", x0, 10");
		lines.add("  ecall");
		lines.add("");
	}

	/* For printing in bootstrap */
	private void emitPrintChar(final char c) {
		lines.add("  addi " + SYSCALL_ARG + ", x0, " + (int)c);
		lines.add("  addi " + SYSCALL_ID + ", x0, 11");
		lines.add("  ecall");
	}

	private void emitPrintString(final String text) {
		for (int i = 0; i < text.length(); i++)
			emitPrintChar(text.charAt(i));
	}

	/**
	 * Emits one function with a prologue, its body, and an epilogue at its exit label.
	 */
	private void emitCodeChunk(final ASM.CodeChunk codeChunk, final LinkedHashMap<MEM.Temp, String> registerMap) {
		if ((codeChunk.entryLabel == null) || (codeChunk.exitLabel == null))
			throw new Report.InternalError();

		final Vector<String> savedRegisters = savedRegisters(registerMap);
		final long registerBase = registerSaveBase(codeChunk.frame);
		final long frameSize = finalFrameSize(codeChunk.frame, savedRegisters);

		lines.add(codeChunk.frame.label.name + ":");
		emitPrologue(codeChunk, savedRegisters, registerBase, frameSize);

		for (final ASM.Instruction instruction : codeChunk.instructions()) {
			final String rendered = render(instruction, registerMap);
			if (rendered == null)
				continue;

			if (definesLabel(instruction, codeChunk.exitLabel)) {
				lines.add(rendered);
				emitEpilogue(codeChunk, savedRegisters, registerBase, frameSize, registerMap);
				continue;
			}

			lines.add(indentIfInstruction(rendered));
		}

		lines.add("");
	}

	/**
	 * Emits the function prologue.
	 */
	private void emitPrologue(
		final ASM.CodeChunk codeChunk,
		final Vector<String> savedRegisters,
		final long registerBase,
		final long frameSize
	) {
		final long oldFpOffset = oldFramePointerOffset(codeChunk.frame);
		final long returnAddressOffset = returnAddressOffset(codeChunk.frame);

		emitSubFromSP(frameSize);

		for (int i = 0; i < savedRegisters.size(); i++)
			emitStore(savedRegisters.get(i), registerBase + 8L * i);

		emitStore("x8", oldFpOffset);
		emitStore("x1", returnAddressOffset);
		emitSetFP(frameSize);
		lines.add("  jal x0, " + codeChunk.entryLabel.name);
	}

	/**
	 * Emits the function epilogue.
	 */
	private void emitEpilogue(
		final ASM.CodeChunk codeChunk,
		final Vector<String> savedRegisters,
		final long registerBase,
		final long frameSize,
		final LinkedHashMap<MEM.Temp, String> registerMap
	) {
		final long oldFpOffset = oldFramePointerOffset(codeChunk.frame);
		final long returnAddressOffset = returnAddressOffset(codeChunk.frame);

		lines.add("  sd " + renderTemp(codeChunk.frame.RV, registerMap) + ", 0(x8)");

		for (int i = savedRegisters.size() - 1; i >= 0; i--)
			emitLoad(savedRegisters.get(i), registerBase + 8L * i);

		emitLoad("x1", returnAddressOffset);
		emitLoad("x8", oldFpOffset);
		emitAddToSP(frameSize);
		lines.add("  jalr x0, x1, 0");
	}

	/**
	 * Emits runtime functions used by external declarations.
	 *
	 * Ripes environment calls use a7 for the call number and a0 for the first
	 * argument/result. The concrete call numbers match Ripes' documented console
	 * services where available.
	 */
	private void emitRuntime() {
		lines.add("_putint:");
		emitRuntimeSave();
		lines.add("  ld " + SYSCALL_ARG + ", 24(x2)");
		lines.add("  addi " + SYSCALL_ID + ", x0, 1");
		lines.add("  ecall");
		emitRuntimeRestore();
		lines.add("  jalr x0, x1, 0");
		lines.add("");

		lines.add("_putchar:");
		emitRuntimeSave();
		lines.add("  ld " + SYSCALL_ARG + ", 24(x2)");
		lines.add("  addi " + SYSCALL_ID + ", x0, 11");
		lines.add("  ecall");
		emitRuntimeRestore();
		lines.add("  jalr x0, x1, 0");
		lines.add("");

		lines.add("_getint:");
		emitRuntimeSave();
		lines.add("  addi " + SYSCALL_ID + ", x0, 5");
		lines.add("  ecall");
		lines.add("  sd " + SYSCALL_ARG + ", 16(x2)");
		emitRuntimeRestore();
		lines.add("  jalr x0, x1, 0");
		lines.add("");

		lines.add("_getchar:");
		emitRuntimeSave();
		lines.add("  addi " + SYSCALL_ID + ", x0, 12");
		lines.add("  ecall");
		lines.add("  sd " + SYSCALL_ARG + ", 16(x2)");
		emitRuntimeRestore();
		lines.add("  jalr x0, x1, 0");
		lines.add("");

		lines.add("_new:");
		emitRuntimeSave();
		lines.add("  ld " + SYSCALL_ARG + ", 24(x2)");
		lines.add("  addi " + SYSCALL_ID + ", x0, 9");
		lines.add("  ecall");
		lines.add("  sd " + SYSCALL_ARG + ", 16(x2)");
		emitRuntimeRestore();
		lines.add("  jalr x0, x1, 0");
		lines.add("");

		lines.add("_del:");
		lines.add("  jalr x0, x1, 0");
		lines.add("");

		lines.add("_exit:");
		lines.add("  addi " + SYSCALL_ID + ", x0, 10");
		lines.add("  ecall");
	}

	/**
	 * Saves Ripes environment-call registers that are also available to register allocation.
	 */
	private void emitRuntimeSave() {
		lines.add("  addi x2, x2, -16");
		lines.add("  sd " + SYSCALL_ARG + ", 0(x2)");
		lines.add("  sd " + SYSCALL_ID + ", 8(x2)");
	}

	/**
	 * Restores syscall registers saved by {@link #emitRuntimeSave()}.
	 */
	private void emitRuntimeRestore() {
		lines.add("  ld " + SYSCALL_ID + ", 8(x2)");
		lines.add("  ld " + SYSCALL_ARG + ", 0(x2)");
		lines.add("  addi x2, x2, 16");
	}

	/**
	 * Writes final assembly to disk.
	 */
	private void write(final String dstFileName) {
		try (final PrintWriter writer = new PrintWriter(new FileWriter(dstFileName))) {
			for (final String line : lines)
				writer.println(line);
		} catch (final IOException __) {
			throw new Report.Error("Cannot write destination file '" + dstFileName + "'.");
		}
	}

	/**
	 * Returns the physical registers used by one function body.
	 */
	private Vector<String> savedRegisters(final LinkedHashMap<MEM.Temp, String> registerMap) {
		final LinkedHashSet<String> saved = new LinkedHashSet<String>(registerMap.values());
		return new Vector<String>(saved);
	}

	/**
	 * Computes how many spill slots were added by register allocation.
	 */
	private long spillSize(final MEM.Frame frame) {
		final long spillSize = frame.size - frame.argsSize - 16 - frame.locsSize;
		if (spillSize < 0)
			throw new Report.InternalError();
		return spillSize;
	}

	/**
	 * Computes where saved physical registers start inside the frame.
	 */
	private long registerSaveBase(final MEM.Frame frame) {
		return frame.argsSize + 16 + spillSize(frame);
	}

	/**
	 * Computes where the old frame pointer is saved inside the frame.
	 */
	private long oldFramePointerOffset(final MEM.Frame frame) {
		return frame.argsSize;
	}

	/**
	 * Computes where the return address is saved inside the frame.
	 */
	private long returnAddressOffset(final MEM.Frame frame) {
		return frame.argsSize + 8;
	}

	/**
	 * Computes the frame size after saved-register slots are added.
	 */
	private long finalFrameSize(final MEM.Frame frame, final Vector<String> savedRegisters) {
		return frame.size + 8L * savedRegisters.size();
	}

	/**
	 * Emits SP -= size.
	 */
	private void emitSubFromSP(final long size) {
		if (isImm12(-size)) {
			lines.add("  addi x2, x2, " + (-size));
			return;
		}

		emitLoadConst(SCRATCH, size);
		lines.add("  sub x2, x2, " + SCRATCH);
	}

	/**
	 * Emits SP += size.
	 */
	private void emitAddToSP(final long size) {
		if (isImm12(size)) {
			lines.add("  addi x2, x2, " + size);
			return;
		}

		emitLoadConst(SCRATCH, size);
		lines.add("  add x2, x2, " + SCRATCH);
	}

	/**
	 * Emits FP = SP + frameSize.
	 */
	private void emitSetFP(final long frameSize) {
		if (isImm12(frameSize)) {
			lines.add("  addi x8, x2, " + frameSize);
			return;
		}

		emitLoadConst(SCRATCH, frameSize);
		lines.add("  add x8, x2, " + SCRATCH);
	}

	/**
	 * Emits a store to the current stack frame.
	 */
	private void emitStore(final String register, final long offset) {
		if (isImm12(offset)) {
			lines.add("  sd " + register + ", " + offset + "(x2)");
			return;
		}

		emitFrameAddress(offset);
		lines.add("  sd " + register + ", 0(" + SCRATCH + ")");
	}

	/**
	 * Emits a load from the current stack frame.
	 */
	private void emitLoad(final String register, final long offset) {
		if (isImm12(offset)) {
			lines.add("  ld " + register + ", " + offset + "(x2)");
			return;
		}

		emitFrameAddress(offset);
		lines.add("  ld " + register + ", 0(" + SCRATCH + ")");
	}

	/**
	 * Emits SCRATCH = SP + offset.
	 */
	private void emitFrameAddress(final long offset) {
		emitLoadConst(SCRATCH, offset);
		lines.add("  add " + SCRATCH + ", x2, " + SCRATCH);
	}

	/**
	 * Emits code that loads a constant into a register.
	 */
	private void emitLoadConst(final String register, final long value) {
		if (isImm12(value)) {
			lines.add("  addi " + register + ", x0, " + value);
			return;
		}

		boolean started = false;
		for (int shift = 56; shift >= 0; shift -= 8) {
			final long byteValue = (value >>> shift) & 0xFFL;
			if (!started) {
				if ((byteValue == 0) && (shift > 0))
					continue;
				lines.add("  addi " + register + ", x0, " + byteValue);
				started = true;
				continue;
			}

			lines.add("  slli " + register + ", " + register + ", 8");
			if (byteValue != 0)
				lines.add("  addi " + register + ", " + register + ", " + byteValue);
		}

		if (!started)
			lines.add("  addi " + register + ", x0, 0");
	}

	/**
	 * Renders one instruction and removes redundant physical-register moves.
	 */
	private String render(final ASM.Instruction instruction, final LinkedHashMap<MEM.Temp, String> registerMap) {
		if (isRedundantMove(instruction, registerMap))
			return null;

		final StringBuilder formatted = new StringBuilder();

		for (int i = 0; i < instruction.instruction.length(); i++) {
			if ((instruction.instruction.charAt(i) != '*') || (i + 2 >= instruction.instruction.length())) {
				formatted.append(instruction.instruction.charAt(i));
				continue;
			}

			final char kind = instruction.instruction.charAt(i + 1);
			if ((kind != 'd') && (kind != 's') && (kind != 'l')) {
				formatted.append(instruction.instruction.charAt(i));
				continue;
			}

			int j = i + 2;
			while ((j < instruction.instruction.length()) && Character.isDigit(instruction.instruction.charAt(j)))
				j++;
			if (j == i + 2) {
				formatted.append(instruction.instruction.charAt(i));
				continue;
			}

			final int index = Integer.parseInt(instruction.instruction.substring(i + 2, j));
			formatted.append(renderPlaceholder(kind, index, instruction, registerMap));
			i = j - 1;
		}

		return formatted.toString();
	}

	/**
	 * Checks whether a move copies a physical register to itself.
	 */
	private boolean isRedundantMove(final ASM.Instruction instruction, final LinkedHashMap<MEM.Temp, String> registerMap) {
		if (!instruction.isMove || (instruction.outputs().size() != 1) || (instruction.inputs().size() != 1))
			return false;

		return renderTemp(instruction.outputs().get(0), registerMap).equals(renderTemp(instruction.inputs().get(0), registerMap));
	}

	/**
	 * Renders one instruction-template placeholder.
	 */
	private String renderPlaceholder(
		final char kind,
		final int index,
		final ASM.Instruction instruction,
		final LinkedHashMap<MEM.Temp, String> registerMap
	) {
		return switch (kind) {
		case 'd' -> renderTemp(instruction.outputs().get(index), registerMap);
		case 's' -> renderTemp(instruction.inputs().get(index), registerMap);
		case 'l' -> instruction.labels().get(index).name;
		default -> throw new Report.InternalError();
		};
	}

	/**
	 * Renders one temporary as a physical register.
	 */
	private String renderTemp(final MEM.Temp temp, final LinkedHashMap<MEM.Temp, String> registerMap) {
		if (RegAll.isFixedRegister(temp))
			return RegAll.fixedRegisterName(temp);

		final String register = registerMap.get(temp);
		if (register == null)
			throw new Report.InternalError();

		return register;
	}

	/**
	 * Returns true if an instruction defines a selected label.
	 */
	private boolean definesLabel(final ASM.Instruction instruction, final MEM.Label label) {
		return instruction.instruction.endsWith(":") && instruction.labels().contains(label);
	}

	/**
	 * Adds indentation to non-label instructions.
	 */
	private String indentIfInstruction(final String line) {
		return line.endsWith(":") ? line : "  " + line;
	}

	/**
	 * Returns true if a value fits into a signed 12-bit immediate field.
	 */
	private boolean isImm12(final long value) {
		return -2048 <= value && value <= 2047;
	}
}
