.PHONY	: all clean

all	:
	if [ -d prev26lang/phase/lexan ] ; then $(MAKE) -C prev26lang/phase/lexan ; fi
	if [ -d prev26lang/phase/synan ] ; then $(MAKE) -C prev26lang/phase/synan ; fi

clean	:
	if [ -d prev26lang/phase/lexan ] ; then $(MAKE) -C prev26lang/phase/lexan clean ; fi
	if [ -d prev26lang/phase/synan ] ; then $(MAKE) -C prev26lang/phase/synan clean ; fi
